# Generated by Django 4.0.3 on 2022-03-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image_path',
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='images/html.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
