# Generated by Django 4.0.3 on 2022-03-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_blog_image_path_blog_image_alter_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='images/tiger2.jpg', upload_to='images/'),
        ),
    ]
