# Generated by Django 4.0.3 on 2022-03-29 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='btntext',
        ),
    ]
